// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSpacePort;

namespace TheSpacePort.db.Migrations
{
    [DbContext(typeof(SpacePortContext))]
    [Migration("20200326155428_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheSpacePort.Parking", b =>
                {
                    b.Property<int>("ParkingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParkingCost")
                        .HasColumnType("int");

                    b.Property<int>("ParkingSpaceLength")
                        .HasColumnType("int");

                    b.Property<int?>("StarshipID")
                        .HasColumnType("int");

                    b.HasKey("ParkingID");

                    b.HasIndex("StarshipID");

                    b.ToTable("parkings");
                });

            modelBuilder.Entity("TheSpacePort.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarshipID")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("StarshipID");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("TheSpacePort.Starship", b =>
                {
                    b.Property<int>("StarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StarshipID");

                    b.ToTable("starships");
                });

            modelBuilder.Entity("TheSpacePort.Parking", b =>
                {
                    b.HasOne("TheSpacePort.Starship", "Starship")
                        .WithMany()
                        .HasForeignKey("StarshipID");
                });

            modelBuilder.Entity("TheSpacePort.Person", b =>
                {
                    b.HasOne("TheSpacePort.Starship", "Starship")
                        .WithMany()
                        .HasForeignKey("StarshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
