// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSpacePort;

namespace TheSpacePort.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheSpacePort.Parking", b =>
                {
                    b.Property<int>("ParkingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParkingCost")
                        .HasColumnType("int");

                    b.Property<int>("ParkingSpaceLength")
                        .HasColumnType("int");

                    b.Property<int?>("SpacePortID")
                        .HasColumnType("int");

                    b.Property<int>("StarshipID")
                        .HasColumnType("int");

                    b.HasKey("ParkingID");

                    b.HasIndex("SpacePortID");

                    b.ToTable("parkings");
                });

            modelBuilder.Entity("TheSpacePort.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("people");
                });

            modelBuilder.Entity("TheSpacePort.SpacePort", b =>
                {
                    b.Property<int>("SpacePortID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableParking")
                        .HasColumnType("int");

                    b.HasKey("SpacePortID");

                    b.ToTable("spacePorts");
                });

            modelBuilder.Entity("TheSpacePort.Starship", b =>
                {
                    b.Property<int>("StarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("StarshipID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("starships");
                });

            modelBuilder.Entity("TheSpacePort.Parking", b =>
                {
                    b.HasOne("TheSpacePort.SpacePort", null)
                        .WithMany("Parkings")
                        .HasForeignKey("SpacePortID");
                });

            modelBuilder.Entity("TheSpacePort.Starship", b =>
                {
                    b.HasOne("TheSpacePort.Person", null)
                        .WithOne("starship")
                        .HasForeignKey("TheSpacePort.Starship", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
